### ISSUE TITLE
Quote mark in text breaks escaping

### ISSUE THREAD

**Issue by HitcherUK** [phil65/script.toolbox#5]
This was the problem biography -

`Sigourney Weaver (born October 8, 1949, height 5' 11" (1,80 m)) is an American actress best known for her role as Ellen Ripley in the Alien film series, a role for which she has received worldwide recognition. Other notable roles include the Ghostbusters films, Gorillas in the Mist, The Ice Storm, Working Girl, Death and the Maiden, Prayers for Bobby and Avatar.`

Because there's a `"` mark used for inches the text stops at the next comma so you end up with this instead -

`Sigourney Weaver (born October 8, 1949, height 5' 11" (1,80 m)) is an American actress best known for her role as Ellen Ripley in the Alien film series,`

**Comment by phil65** [comment]
Please also post your exact script call.

**Comment by HitcherUK** [comment]
`<onclick>RunScript(script.toolbox,info=textviewer,header=,text='"$INFO[Window.Property(Biography)]"')</onclick>`

**Comment by HitcherUK** [comment]
@phil65 Here's an easy way to test -

`RunScript(script.toolbox,info=textviewer,header=$INFO[ListItem.Label],text='"Testing" 1, 2, 3."')`

**Comment by HitcherUK** [comment]
Did some more testing and it seems I can remove the escaping quotes from Extended Info's `$INFO[Window.Property(Biography)]` and it works correctly.

`RunScript(script.toolbox,info=textviewer,header=,text=$INFO[Window.Property(Biography)])`

The escaping quotes are still needed for other text though and they still appear in the output text but I'll close this and open other issue for that problem.

Thanks.

**Comment by HitcherUK** [comment]
Sorry, I was too hasty. Removing them works for that particular biography with a single `"` in it but not others. So it seems to me that if there's an odd number of `"` in the info label then escaping will break at the next comma.

**Comment by phil65** [comment]
Yup, might be.  Perhaps a better solution would be to let skinners write the text into a window property instead of passing it via a parameter. That would avoid all these problems completely.

**Comment by HitcherUK** [comment]
So add another onclick that sets the property along with the textviewer one?
